### ISSUE TITLE
Encoding data segment alignment and BSS size

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/tool-conventions#12]
In order for a linker to lay out static data from different object it needs to know the alignment of each object data segment(s).

We also need to know the total static data size (including bss).

In the current s2wasm world the latter is encoded via the "staticBump" metadata field which s2wasm produces.  The former is not a problem since llmv-link does this part.

So I think we need to store this information in each relocatable wasm object.  The question is then how should we store it?  We could create specially named global "__data_alignment" and "__data_size", or we could add these as entries in the linking metadata section?  I'm leaning towards the latter, especially since down the line we may end up with many data segments per object (-fdata-sections).

**Comment by sbc100** [comment]
@sunfishcode @dschuff , thoughts?

**Comment by dschuff** [comment]
Linking metadata seems better to me too. In the future we might also have some other kind of per-section metadata (e.g. readonly) so it would work better for that too.

**Comment by binji** [comment]
Or my hack idea to use the first offset of the first data segment as the alignment:

```
(memory 1)
(data (i32.const 32) "...")  ;; Align to 32 bytes
```

:-D

**Comment by sunfishcode** [comment]
@binji That is a clever hack :-). However, I agree with @dschuff; the linking metadata approach seems better. Segment offsets exist to save file size when lots of zeros are needed, so it's conceptually cleaner to avoid overloading them with a second purpose.

**Comment by sbc100** [comment]
A followup to this: https://github.com/WebAssembly/tool-conventions/issues/33

**Comment by sbc100** [comment]
For alignment we solve this issue with SEGMENT_INFO metadata.

We have not yet solved the BSS issue but that can most likely be done in the same metadata.
