### ISSUE TITLE
"Merging Data Sections" in Linking.md is out of date

### ISSUE THREAD

**Issue by binji** [WebAssembly/tool-conventions#18]
See https://github.com/WebAssembly/tool-conventions/blob/master/Linking.md#merging-data-sections.

Speaking with @sbc100, it seems like this section is no longer correct. For example, it refers to `R_DATA` which no longer exists, and it mentions using `get_global` where the current model has different relocations depending on where the memory address is used. It probably should be updated.

**Comment by sbc100** [comment]
This is fixed now.
