### ISSUE TITLE
C enum size

### ISSUE THREAD

**Issue by yamt** [WebAssembly/tool-conventions#187]
https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md says enum is 4-bytes.

otoh, clang sometimes yields 8-bytes enum.
eg.
```
enum e {
        a = 0x100000000,
};
```

which should be fixed?

**Comment by yamt** [comment]
> which should be fixed?

my suggestion is to amend BasicCABI.md.
but i'm totally ignorant of the situations of other compilers.

**Comment by sunfishcode** [comment]
Would changing it to say "`enum` (by default)" make it clear?

**Comment by yamt** [comment]
my suggestion https://github.com/WebAssembly/tool-conventions/pull/188

**Comment by dschuff** [comment]
Fixed by #188
