### ISSUE TITLE
Clarify integer data representation rule in BasicCABI

### ISSUE THREAD

**Issue by FanShupei** [WebAssembly/tool-conventions#218]
In BasicCAPI, it says how C types are represented by wasm types, but it lacks details how to actually do the conversion.

Specifically, I have two concrete questions to ask?
- In return site, i8/u8/i16/u16 are sign/zero-extended to i32, or higher bits may contain garbage data?
- In parameter site, is it valid for the callee function to assume i8/u8/i16/u16 are always correctly sign/zero-extended?

It's not hard to find out the answer for current clang implementation.
- For the first question, i8/i16 are sign-extended, u8/u16 are zero-extended.
- For the second question, the answer is yes, based on current clang implementation.

However, I'd like to confirm whether this is the intended behavior. If yes, we'd better clarify it in documentation.

**Comment by dschuff** [comment]
Yes, I think this is the behavior we intend, and I agree that the documentation should clarify it. I can work on a PR for that.
