### ISSUE TITLE
--target=wasm32-unknown-unknown:  'stdio.h' file not found

### ISSUE THREAD

**Issue by ahaoboy** [WebAssembly/tool-conventions#227]
When setting target to wasm32-unknown-unknown, `stdio.h` is not found.

```c
#include <stdio.h>
#include <stdint.h>
```

```bash
 bindgen ./test.h -o test.rs  -- --target=wasm32-unknown-unknown
```

```
./test.h:1:10: fatal error: 'stdio.h' file not found
panicked at bindgen-cli/main.rs:52:36:
Unable to generate bindings: ClangDiagnostic("./test.h:1:10: fatal error: 'stdio.h' file not found\n")

```
stdlib.h also has the same problem
```
'stdlib.h' file not found
```

**Comment by jedisct1** [comment]
Issues regarding `bindgen` would be better opened in the [bindgen repository](https://github.com/rust-lang/rust-bindgen).

Anyway, the easiest way is to [run bindgen in your build.rs file](https://rust-lang.github.io/rust-bindgen/tutorial-3.html) and then just compile your project with [cargo-zigbuild](https://github.com/rust-cross/cargo-zigbuild) (`cargo-zigbuild --target=wasm32-unknown-unknown` or `cargo-zigbuild --target=wasm32-wasi`).

**Comment by ahaoboy** [comment]
>  the easiest way is to [run bindgen in your build.rs file](https://rust-lang.github.io/rust-bindgen/tutorial-3.html) and then just compile your project with [cargo-zigbuild](https://github.com/rust-cross/cargo-zigbuild) (`cargo-zigbuild --target=wasm32-unknown-unknown` or `cargo-zigbuild --target=wasm32-wasi`).

Thx
