### ISSUE TITLE
Question: memory layouts and memory.grow

### ISSUE THREAD

**Issue by tamaroning** [WebAssembly/tool-conventions#229]
I compiled the code below with wasi-sdk clang
```c
#include <stdio.h>

int main(int argc, char** argv) {
    printf("argc: %d\n", argc);
    for (int i = 0; i < argc; i++) {
        printf("argv[%d]: %s\n", i, argv[i]);
    }
    return 0;
}
```
and got the snippet from the generated binary
```
...
  (global $__stack_pointer (mut i32) (i32.const 70816))
  (global $GOT.data.internal.__memory_base i32 (i32.const 0))
  (export "memory" (memory 0))
  (export "_start" (func $_start))
  (elem (;0;) (i32.const 1) func $__stdio_write $__stdio_close $__stdout_write $__stdio_seek)
  (data $.rodata (i32.const 1024)
...
```

I noticed that there are two pages in memory but SP is set to 70816.
I guess each page is allocated to different linear addresses.

However, what behavior is expected when memory.grow is invoked? Should it extend stack pages?
Also I could not find documents about memory layouts. It would be useful when we make wasm interpreters/compilers.

**Comment by kripken** [comment]
> However, what behavior is expected when memory.grow is invoked? Should it extend stack pages?

`memory.grow` grows the entire wasm memory. It has no effect on the data inside the memory. The stack vs the heap is just a matter of how the data inside the memory is used by the wasm program, so growing the memory has no impact. For example, a toolchain could exist that has no stack inside the memory at all (everything is done on the heap).

Specifically for LLVM, it does not grow the stack. That is, the stack size is fixed at compile time. Other toolchains, however, can have growable stacks - I believe Go might do that, but I'm not sure.

**Comment by tamaroning** [comment]
Thank you for your brief answer.

> memory.grow grows the entire wasm memory. It has no effect on the data inside the memory. 

I understand that `memory.grow` changes just the entire memory size so runtimes need to know memory layouts or to implement dynamic memory.
