### ISSUE TITLE
Document Argument passing for _BitInt types

### ISSUE THREAD

**Issue by pinskia** [WebAssembly/tool-conventions#239]
Forwarded from https://hachyderm.io/@kaylie@blahaj.zone/113574803870036780 .

The current BasicCABI.md does not document how _BitInt types are passed and it would be good to document it as such.

Note if someone does a GCC backend for WebAssembly, GCC folks in general has decided the ABI for _BitInt needs to be documented before it having it implemented too.

See https://github.com/ARM-software/abi-aa/issues/175, https://github.com/riscv-non-isa/riscv-elf-psabi-doc/issues/300 and https://gitlab.com/x86-psABIs/x86-64-ABI/-/merge_requests/32 for examples on how other ABIs (have or will have document it).

**Comment by sunfishcode** [comment]
I've now filed #240 to document `_BitInt` and a few other types.
