### ISSUE TITLE
Consider using indices rather than names for symbol identifiers

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/tool-conventions#30]
A `syminfo` currently identifies its symbol by name. It seems like it would be simpler, more consistent with wasm encoding in general, and consistent with the ELF-like principle of not referring to symbols within the same module by name, and possibly faster to link, if it identified symbols by index.

It would also work well with https://github.com/WebAssembly/tool-conventions/issues/29, in case it became important to add symbol flags to local symbols, because local symbols have indices.

It would need some way to indicate the type of index: function, global, table, or memory. I expect we could either split `WASM_SYMBOL_INFO` into 4 codes, `WASM_FUNCTION_SYMBOL_INFO` and so on, or we could add [`external_kind`](https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md#external_kind) bytes.

**Comment by NWilson** [comment]
Under review: https://reviews.llvm.org/D42117

**Comment by sbc100** [comment]
Could you create PR to update Linking.md accordingly?

**Comment by sbc100** [comment]
If we go ahead with this plan then this will be fixed and we will get rid of SYMBOL_INFO completely:
https://github.com/WebAssembly/tool-conventions/issues/38

**Comment by sbc100** [comment]
We can reopen if #38 doesn't happen.

**Comment by NWilson** [comment]
Can close now
