### ISSUE TITLE
Linking function pointers and function relocations must use Symbol not Function index

### ISSUE THREAD

**Issue by NWilson** [WebAssembly/tool-conventions#34]
This arises from https://bugs.llvm.org/show_bug.cgi?id=35625

# First Problem - function pointers

Currently, there is no linking metadata for table entries (function pointers). The Wasm table entry itself is used to find out which function the relocation should be generated for. In order for the Wasm module to pass validation, the table entries in object files _must_ point to a valid Function (code definition).

However, this actually semantically wrong. The linker can't generate correct output simply using the Function index, it needs the actual Symbol.

Here's an example to illustrate:

```
=== file1.c ===
int aliasFn(void) { return 1; }

=== file2.c ===
int directFn(void) { return 2; }
extern int aliasFn(void) __attribute__((weak,alias("directFn")));
int directFnPtr() { return (int)&directFn; }
int aliasFnPtr() { return (int)&aliasFn; }

int callDirect(void) { return directFn(); }

=== Results ===
Compile and link with `lld file1.o file2.o`.
 * directFnPtr and aliasFnPtr should point to two different methods, but
   unfortunately they don't.
 * If file2 is compiled with -O0 (to prevent inlining) then callDirect erroneously
   returns 1
```

(The output Wasm module for this has three functions: directFn, directFnPtr, aliasFnPtr. The table entries can only point to those. It has four exports (=symbols): directFn, aliasFn, directFnPtr, aliasFnPtr.)

The relocations for directFnPtr and aliasFnPtr will both reference Wasm table entries - and those table entries both point to directFn! The relocations are completely indistinguishable... yet, upon linking, we may need those two function to be relocated to point to different functions (if another file provides "aliasFn" more strongly or earlier).

# Second problem - function relocations

Even worse, function relocations are also broken by aliases! Oops. In the example above, LLD happens to use the Symbol for "aliasFn" as the Symbol associated with the body of "directFn". That's actually completely reasonable behaviour - we have here two different Symbols/names associated with the same function body, it's a toss of a coin which one is chosen. There is no single "canonical" Symbol referring to the Function body.

Attempts to call "directFn" directly (not even via a pointer!) will also generate incorrect code currently. This is because the last-defined Symbol for a function wins, and so the relocation is generated against aliasFn.

In the linking metadata for relocations, we _can't_ use the Function index, we have to use the Symbol index instead.

**Comment by NWilson** [comment]
Note - I ran into this on real code. For simple classes, the C++ frontend generates the symbols `_ZN<NAME>C2Ev` and `_ZN<NAME>C1Ev` as aliases to the same function body (when it's not inlined), and it seems that the address of the aliased constructor is sometimes taken, resulting in it going into the function-pointer table.

You might not expect aliases to be common enough to worry about, but I think we do need to get this right for C++ support.

**Comment by sbc100** [comment]
Yes, looks like we do indeed have a problem with aliases. 

In your proposed solution, what do you mean by "Symbol index"?  I don't think we have such a concept right now do we?  Assuming that we did have such a concept, would it be sufficient to add relocation entries for all the table entries? (assuming that relocation reference symbols) .  This would avoid creating a new metadata section, and seems like a good use relocations.

**Comment by sbc100** [comment]
This also makes me wonder if we are modeling aliases in the most sensible way.  Perhaps there is a better one.

**Comment by sbc100** [comment]
I think maybe this used to work before I landed this: https://reviews.llvm.org/D38246

**Comment by NWilson** [comment]
Some interesting ideas... you could be right that it used to work, and it's worth considering whether weak symbols are modelled correctly.

Currently (despite a comment in WasmObjectWriter to the contrary), all symbols in a file are exported, including local ones, so the list of Exports covers every function: I think I'm right that there are no un-exported Functions? So Exports are mapped many-to-one and "onto"/surjectively to Functions. Finally, imports are completely disjoint from Exports/Functions.

I conclude that the concepts are mapped correctly to Wasm. Having something in both Imports/Exports is muddying the waters of what those concepts represent, whereas currently the mapping from LLVM to Wasm concepts is clear and correct. "Imports" are symbols pulled in from outside, "Exports" are symbols defined by the file, with various flags. The Types+Code vectors are the actual function bodies that symbols point to, and aren't used directly by the linker, which works on the level of Symbols.

It really is just the index spaces that aren't quite right, following on from that change.

## Proposal

1. Let's define the "Wasm index space of functions" as `[0,NumImportedFunctions)` plus `[NumImportedFunctions,NumImportedFunctions+NumCodeFunctions)`. This is what is used for Wasm validation, when an index needs to refer to something "executable", eg a Table Element.
2. Similarly, the "Wasm index space of globals"
3. Now let's define a new index space, the "Symbol index space of functions" as `[0,NumImportedFunctions)` plus `[NumImportedFunctions,NumImportedFunctions+NumExportedFunctions)`. This the linker-level index space of things that you can meaningfully link to. Relocations against function indices would use a "Symbol index", which will be resolved into the "Wasm index space" when the relocation is actually applied.
4. Similarly the "Symbol index space of globals"
5. Finally, because we have this notion that the object file should be a semi-valid Wasm file, it does make sense to keep the existing Table with its elements in the "Wasm index space of functions".
6. But, for the benefit of the linker we'll need to provide the function indices in the "Symbol index space of functions". Your idea is spot on, to alter the TABLE_INDEX relocation so that the index contained in the relocation is a Symbol index, rather than the index of a Table entry. Then, the linker will completely ignore the input Table, and build a table containing an entry for every address-taken function, using the just the information from relocations. It will rewrite the TABLE_INDEX items from the Symbol index to the Table index of the Symbol's resolved function. You're absolutely right, we don't need a new linking metadata section when the existing relocation will do.

These changes would affect relocations of type TABLE_INDEX, FUNCTION_INDEX, and GLOBAL_INDEX.

To be honest, I don't think that table indices could have possibly worked before D38246 landed? The table simply won't validate if the values stored in the table are too big, and there are (in general) more exports that imports due to aliases.

**Comment by NWilson** [comment]
Also related:
* https://github.com/WebAssembly/tool-conventions/issues/30. The Symbol-info linking-metadata should link to objects by index rather than name, for compactness.
* The "name" custom section is completely superfluous. All symbols are exported now, including locals, and I think that's appropriate, since as Symbols they participate in all the normal linker features, like alias resolution, relocations etc. WasmObjectFile currently does some odd stuff where it creates "DEBUG_NAME" WasmSymbols for functions name in the "name" section - I think that's just odd and could be deleted. LLD can ignore the "names" section when reading in a relocatable Wasm file. We can happily write out a "name" section for use by browser debuggers though, there's no harm to that.

**Comment by sbc100** [comment]
Re: your last proposal above.

(1) and (2) are already pretty well defined and well understood in the wasm world I think so we already have those concepts.

(3) and (4) sounds la bit like what building a separate symbol space, which I have also been thinking about for a while now.  I would suggest that if might as well use a single symbol space for all symbols (both globals and function) if we are going to break away from (1) and (2).  This is more in line with existing linkers.  I like the idea of relocations referencing symbols. 

I've been running into issues recently that have also suggested we might need a separate symbol space, but I can't remember exactly what they were.

Is it your understanding that aliases (functions with multiple names) are currently the feature that is forcing us down this road?

How do you you thinking we should represent the symbol table in (3) and (4) in the object format? I was thinking we could add linking:SYM_TABLE and have all symbols information there (including the string names).  That way COMDAT names can also live there, and its easy for things like relocations to refer to  single "symbol" index.  I will open another issue do discuss craeting a symbol table if you agree this a the right way to go.

**Comment by sbc100** [comment]
I found a interm solution to this problem: https://reviews.llvm.org/D41472

There may still be a need for a more extensive move to symbol table but I think this will be enough to fix the above cases.

**Comment by sbc100** [comment]
@NWilson are you on IRC by any chance (i'm sbc100 on OFTC)?  Since we are working so closely on this stuff it might be useful to chat in real time?   (or we could try hangout?, I'm sbc@google.com there).

**Comment by NWilson** [comment]
> (1) and (2) are already pretty well defined and well understood in the wasm world I think so we already have those concepts.

Yes, I just defined some terminology for what's already there ("Wasm index space"), and wrote it out to show the contrast to the "Symbol index space".

> (3) and (4) sounds la bit like what building a separate symbol space, which I have also been thinking about for a while now. I would suggest that if might as well use a single symbol space for all symbols (both globals and function) if we are going to break away from (1) and (2). This is more in line with existing linkers. I like the idea of relocations referencing symbols.

An interesting idea; it would be possible to have combined function and globals index space. However, I do like the way Wasm separates out function/global indexes: with a combined space you need to do `if (I < Symbols.size() && Symbols[I].isFunction()) doThing()` whereas with separate indices for functions/globals it's just a range-check `if (I < FunctionSymbols.size()) doThing()`. Wasm clearly wanted a single range check for perf reasons; in LLD I think we should prefer a single range-check just for type safety. Every time you read from a combined index space you need a test or an assertion, or risk adding a bug if you don't check/assert. There are hardly any valid reasons in a linker to be using symbol, and not know whether it refers to a function or global.

> I've been running into issues recently that have also suggested we might need a separate symbol space, but I can't remember exactly what they were.
> 
> Is it your understanding that aliases (functions with multiple names) are currently the feature that is forcing us down this road?

Yes, I think so. Without aliases, there would be a one-to-one mapping between function-exports and code definitions, and global-exports and global definitions. Pesky isn't it... Aliases are useful in practice though, and places in Musl (for example) that use weak aliases do highlight some genuinely worthwhile use-cases.

> How do you you thinking we should represent the symbol table in (3) and (4) in the object format? I was thinking we could add linking:SYM_TABLE and have all symbols information there (including the string names). That way COMDAT names can also live there, and its easy for things like relocations to refer to single "symbol" index. I will open another issue do discuss craeting a symbol table if you agree this a the right way to go.

I was actually thinking that the "symbol table" wouldn't ever exist in the object format. It can be completely implicit, since it's just the union of the imports+exports, in the same that Wasm currently has an implicit "Wasm function index space" that's the union of imports+code.

Our existing SYM_INFO linking metadata works fine, and I don't think it _needs_ any changes. (It currently has a list of `{imported/exported-name, flags}` pairs used to attach flags to the imports/exports. It would be more compact if it switched to `{global/function-kind-bool, symbol-index, flags}` but that's purely a filesize optimisation and would have identical behaviour.)

> @NWilson are you on IRC by any chance (i'm sbc100 on OFTC)? Since we are working so closely on this stuff it might be useful to chat in real time? (or we could try hangout?, I'm sbc@google.com there).

With the 8-hour time difference it's a bit awkward. I'm heading home when you wake up and having dinner with family when it's 10am for you... I'm trying to answer emails a bit during the evening, so you don't have to wait 24hrs for replies, but I try not to work much at home, especially over Christmas. I hope you enjoy some holiday!

**Comment by sbc100** [comment]
Thinking about this more, and looking at your current proposed changes, I'm leaning more and more towards creating an explicit symbol table.

This seems like the logical answer to "imports and exports" are not quite enough to model what we need.  Rather than trying to build and implicit symbol table from imports and exports lets just be explicit about it.   It would also allow us to completely remove the imports and exports of globals which we currently use to model data addresses.  Using wasm globals for this seemed like a good idea at the time but doesn't make a lot of sense.

My proposal would be to add a new "symtab" section (or subsection?) that would replace the current "syminfo" subsection.   Every symbol in the object would require an entry in this table.    For data symbols the name would be included here in the table.  For function symbols the name could refer to function import or export so avoid duplicating the name.   The symbol index would then be explicit and all relocations would then refer to symbols in this table.  The exception would be type relocations for which there is no name or symbol yet.. but we could consider making symbols for types too.

@NWilson, I'm not proposing that we don't land more of the patches you have sent.  Most of them are valuable independently, but this does conflict with the final link in the chain: https://reviews.llvm.org/D42117

**Comment by sbc100** [comment]
See https://github.com/WebAssembly/tool-conventions/issues/38

**Comment by NWilson** [comment]
Hmm, having an explicit symbol table... that would a lot of extra work - but doable. I'll comment on #38.

The review for this ticket is https://reviews.llvm.org/D41954, in which each symbol is modelled by a single import or export, depending on whether it's a undefined/defined. That at least is a step forward on its own.

**Comment by NWilson** [comment]
Closed by https://github.com/WebAssembly/tool-conventions/issues/38
