### ISSUE TITLE
Have linking look for `.imports` alongside each `.a`.

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/tool-conventions#35]
Currently we rely on the clang driver adding `-allow-undefined-file wasm.syms` along with `-lc`.  Without this (if -lc is used on its own) symbols such as syscalls will cause the link to fail.

I propose that we have the linker looks for an optional `.imports` files alongside each library can can list symbols which that library expects the wasm embedder to provide.    We can then rename `wasm.syms` to `libc.imports` and remove the `-allow-undefined-file` from the driver.

**Comment by sbc100** [comment]
LLD change: https://reviews.llvm.org/D41922

**Comment by sbc100** [comment]
Clang driver change: https://reviews.llvm.org/D41923

**Comment by sbc100** [comment]
waterfall change: https://github.com/WebAssembly/waterfall/pull/309

**Comment by sbc100** [comment]
musl change: https://github.com/jfbastien/musl/pull/34

**Comment by NWilson** [comment]
Funny, I have a branch I haven't yet turned into a PR where I was thinking along the same lines! I was going to take the easier route of renaming the (extremely generic) "wasm.syms" to "libc.syms". But I hadn't considered removing the `-allow-undefined-file` argument.
