### ISSUE TITLE
dylink naming conventions, camelCase vs. under_score

### ISSUE THREAD

**Issue by jayphelps** [WebAssembly/tool-conventions#62]
I should probably apologize in advance for bikeshedding this. 😞

I'm curious if it's too late to consider having a consistent naming convention for dynamic linking. We have `__post_instantiate` using an under_score separator and prefix, and `memoryBase`, `tableBase` with camelCase no prefix. Do these have any other historical significance? Just emscripten?

I don't think we'll ever agree on which is _better_, so I'm wondering if we compromise and instead use all lowercase, double under_score prefix. The lowercase form _feels_ less opinionated and more low-level, although I can't exactly quantify why I feel that way.

- `__postinstantiate`
- `__memorybase`
- `__tablebase`

**Comment by kripken** [comment]
I have no preference myself.

I think it's early enough that we can change this - few people use dynamic linking, and all those that I am aware of are building all their own files, that is, there is no ecosystem yet of people using libraries built by someone else.

**Comment by sbc100** [comment]
I vote for snake_case with underscores.  We are dealing with low level ABI stuff where is this the norm.  

I might also add that perhaps we want to use a wasm prefix so as not to pollute the namespace for tools that live one top of us?  How about `__wasm_post_instanciate`, `__wasm_memory_base` and `__wasm_table_base`?

**Comment by jayphelps** [comment]
@sbc100 works for me, and I dig the namespace.

**Comment by sbc100** [comment]
I believe this is fixed as of #74
