### ISSUE TITLE
Using only .functype directive for both defined and declared functions

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/tool-conventions#72]
In .s assembly, currently we use `.param` and `.result` directives to denote defined function types, as in
```
.param i32, i64
.result i32
```

And `.functype` directive to denote declared (= undefined) function types, as in
```
.functype foo, void, i32, i64  
```
(The first type is the return type)

@sbc100 [suggested](https://bugs.llvm.org/show_bug.cgi?id=39557#c7) that we unify these to just `.functype` directive, so we can use the single `.functype` directive for both defined and declared functions. We currently don't support parsing of `.functype`, but after we do, I think this is a cleaner option. What do you think?

@dschuff @sunfishcode @sbc100 @aardappel

**Comment by aardappel** [comment]
Generally SGTM.
Might it be worth it though to keep 2 directives for declared vs defined? Information is easy to throw away, sometimes not easy to recover.

**Comment by aardappel** [comment]
if we're going to parse it ourselves, can it be something readable like `.functype foo(i32, i64) -> ()` ?

**Comment by aheejin** [comment]
@rossberg Oh that's a good point, thank you.
@aardappel Yeah I think that'd work, what do others think?

**Comment by dschuff** [comment]
As long as it doesn't interfere with the asmparser's existing handling of parens and operators (e.g. https://sourceware.org/binutils/docs/as/Integer-Exprs.html#Integer-Exprs), it seems fine.

**Comment by tlively** [comment]
Should the name of the function be part of the functype, or should it be something like `.functype i32, i64 -> ()`?

**Comment by aardappel** [comment]
The assembler has to explicitly call `parseExpression` for a (part of) a directive to be interpreted as such.

There is no `->` token though, so unless `-` `>` is cool, we should maybe use `:` or something :)

**Comment by aardappel** [comment]
@tlively yes, having the name in there is generally good, which means that these directives can appear anywhere, and keep the assembler dumb & stateless.

**Comment by aheejin** [comment]
Can we add something like `Arrow` (`->`) [here](https://github.com/llvm-mirror/llvm/blob/5617e05f341c24230ce190f30c6752ec2ad3fc73/include/llvm/MC/MCAsmMacro.h#L24-L64)?

**Comment by aardappel** [comment]
@aheejin I'm fine with that too.

**Comment by jgravelle-google** [comment]
Could use `$` as a token to say "switch from params to returns" or vice-versa. `.functype foo i32 $ f32, f64`
Could also just use a whole word, `.functype foo i32 returns f32, f64`, though maybe that doesn't scale to user-defined types?
:bike: :derelict_house:

**Comment by dschuff** [comment]
I like the idea of adding symbol names to the existing directives to make everything stateless.
The downside of separating `.param` from `.result` is that it doesn't match how we handle signatures (which are unified). When we parse a `.param` we don't know if there will be a `.result` so we have to create a signature, store it wherever, and create the association between the symbol and the signature; and then if we see a `.result` we have to go back and do it all again (and ideally delete the first one we made, but only if it's unused...)

**Comment by aheejin** [comment]
I also prefer not separating `.params` and `.results`. We can call `MCSymbolWasm::setSignature` only if we have the full parameter and return type information, like [here](https://github.com/llvm-mirror/llvm/blob/a8f890f4777f53bd9243bfdd9ed2b5d171cc8c03/lib/Target/WebAssembly/WebAssemblyAsmPrinter.cpp#L92-L98),  so separating them actually increases the assembler context.

**Comment by binji** [comment]
How about `→`? :smiling_imp:

**Comment by jgravelle-google** [comment]
How about `▶` for single-return and `⏩` for multi-return?
:clown_face:

**Comment by aardappel** [comment]
Universal `.functype` is being introduced here: https://reviews.llvm.org/D54652
This is using the `.functype foo(i32, i64) -> (i32)` style syntax.

**Comment by aardappel** [comment]
Please comment there if you have further concerns :)
